### ISSUE TITLE
Panic in PipeConfigChunks

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#263]
Looks like my PR #251 introduced a bug which can lead to a panic:

```
panic: runtime error: slice bounds out of range [:3] with capacity 1

goroutine 2886 [running]:
github.com/Icinga/icingadb/connection.(*RDBWrapper).PipeConfigChunks.func3(0xc0003b1860, 0xc00006f630, 0x1f4, 0xc0007733e0)
	/idbcp/connection/redis.go:661 +0x33a
created by github.com/Icinga/icingadb/connection.(*RDBWrapper).PipeConfigChunks
	/idbcp/connection/redis.go:653 +0x145
```

**Comment by N-o-X** [comment]
Shouldn't be a problem anymore with the RC2 changes in place.
