### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string after upgrade to 2.13

### ISSUE THREAD

**Issue by Ramshield** [Icinga/icingadb#332]
## Describe the bug

When starting icingadb please see the full log:

```
-- Logs begin at Wed 2021-08-04 11:05:23 CEST, end at Wed 2021-08-04 11:14:43 CEST. --
Aug 04 11:05:25 icinga systemd[1]: Started Icinga DB.
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Connecting to Redis"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Connecting to MySQL"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Redis connection established"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Starting heartbeat listener"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Serving metrics at http://localhost:8080/metrics"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="SQL connection established"
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Got initial environment." UUID=1709739b-4e0d-4e62-b89f-cfbe13a9cf56 context=HA environment=d
Aug 04 11:05:25 icinga icingadb[355]: time="2021-08-04T11:05:25+02:00" level=info msg="Taking over." UUID=1709739b-4e0d-4e62-b89f-cfbe13a9cf56 context=HA environment=da39a3ee5e6b4
Aug 04 11:05:26 icinga icingadb[355]: panic: interface conversion: interface {} is nil, not string
Aug 04 11:05:26 icinga icingadb[355]: goroutine 151 [running]:
Aug 04 11:05:26 icinga icingadb[355]: github.com/Icinga/icingadb/ha.(*HA).runEventListener(0xc000164180)
Aug 04 11:05:26 icinga icingadb[355]:         /builds/packaging/deb-icingadb/build/icingadb/ha/ha.go:336 +0x471
Aug 04 11:05:26 icinga icingadb[355]: github.com/Icinga/icingadb/ha.(*HA).StartEventListener(0xc000164180)
Aug 04 11:05:26 icinga icingadb[355]:         /builds/packaging/deb-icingadb/build/icingadb/ha/ha.go:306 +0x57
Aug 04 11:05:26 icinga icingadb[355]: created by main.main
Aug 04 11:05:26 icinga icingadb[355]:         /builds/packaging/deb-icingadb/build/icingadb/main.go:143 +0x731
Aug 04 11:05:26 icinga systemd[1]: icingadb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 04 11:05:26 icinga systemd[1]: icingadb.service: Failed with result 'exit-code'.
Aug 04 11:05:26 icinga systemd[1]: icingadb.service: Consumed 36ms CPU time.
```

## To Reproduce

Ran apt dist-upgrade to Upgrade Icinga to 2.13. The issue occurred, then upgrades to latest snapshot, same problem.

## Expected behavior

-

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version:
```
# icingadb --version
Icinga DB version: v1.0.0-rc1
```
* Icinga 2 version:
```
# dpkg -l | grep icinga
ii  icinga-l10n                          1.1.0.20210707.1023+buster-0                 all          l10n (short for Localization) provides all translations available for Icinga.
ii  icinga-php-common                    1.0.0-1.buster                               all          Icinga PHP Common for Icinga Web 2
ii  icinga-php-library                   0.6.1-1.buster                               all          Icinga PHP Library for Icinga Web 2
ii  icinga-php-thirdparty                0.10.0-2.buster                              all          Icinga PHP Thirdparty for Icinga Web 2
ii  icinga-redis                         5.0.10-1.buster                              amd64        Persistent key-value database with network interface (metapackage)
ii  icinga2                              2.13.0+4.g02db80d6f.20210803.1705+buster-0   amd64        host and network monitoring system
ii  icinga2-bin                          2.13.0+4.g02db80d6f.20210803.1705+buster-0   amd64        host and network monitoring system - daemon
ii  icinga2-common                       2.13.0+4.g02db80d6f.20210803.1705+buster-0   all          host and network monitoring system - common files
ii  icinga2-doc                          2.13.0+4.g02db80d6f.20210803.1705+buster-0   all          host and network monitoring system - documentation
ii  icinga2-ido-mysql                    2.13.0+4.g02db80d6f.20210803.1705+buster-0   amd64        host and network monitoring system - MySQL support
ii  icingacli                            2.9.2-1.buster                               all          simple CLI tool for Icingaweb2 and its modules
ii  icingadb                             1.0.0+rc1.72.g26f5dc5.20200924.0835+buster-0 amd64        database connector for Icinga 2
ii  icingadb-redis                       1.0.0+rc1.72.g26f5dc5.20200924.0835+buster-0 amd64        Redis service for Icinga DB
ii  icingaweb2                           2.9.2-1.buster                               all          simple and responsive web interface for Icinga
ii  icingaweb2-common                    2.9.2-1.buster                               all          simple and responsive web interface for Icinga - common files
ii  icingaweb2-module-doc                2.9.2-1.buster                               all          simple and responsive web interface for Icinga - documentation module
ii  icingaweb2-module-monitoring         2.9.2-1.buster                               all          simple and responsive web interface for Icinga - monitoring module
ii  php-icinga                           2.9.2-1.buster                               all          PHP library to communicate with and use Icinga
```
* Operating System and version:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Additional context

-

**Comment by Ramshield** [comment]
So I managed to get it working by actually running the main.go file.
But that doesn't run it as daemon. 
What is the proper way of doing this? Should I compile it with go, as the instructions are unclear to me.

**Comment by lippserd** [comment]
Hi @Ramshield,

Icinga DB v1.0.0-rc1 is not compatible with Icinga 2.13. But we're working on an RC2. You may either use the main branch here or wait for snapshot packages, which we're also currently working on.

If you want to run Icinga DB from Git please do the following:

- Run `go build -o /usr/sbin/icingadb cmd/icingadb/main.go`
- Install the systemd service
- Create `/etc/icingadb/config.yml`

Hope that helps.

Cheers,
Eric

**Comment by Ramshield** [comment]
Hi @lippserd,

Understood, I am now running it from the `main.go`.
Any idea when the snapshot packages are released, can I follow that process somewhere?

Thank you!

**Comment by lippserd** [comment]
@N-o-X We have snapshot packages now, right?
