### ISSUE TITLE
Getting error opening History "createTicketLinks() must be of the type string, null returned"

### ISSUE THREAD

**Issue by pbirokas** [Icinga/icingadb#697]
## Describe the bug
When trying to open the history from some Services or Hosts, I am getting an error. Other work as expected

## To Reproduce
I have no idea!

## Expected behavior
Expected to see the history of all items.

## Screenshots
```
Return value of Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem::createTicketLinks() must be of the type string, null returned

#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/BaseHistoryListItem.php(71): Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem->createTicketLinks(NULL)
Icinga/icingaweb2#1 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(65): Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem->assembleCaption(Object(ipl\Html\HtmlElement))
Icinga/icingaweb2#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/ListItemCommonLayout.php(23): ipl\Web\Common\BaseListItem->createCaption()
Icinga/icingaweb2#3 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(83): Icinga\Module\Icingadb\Widget\ItemList\HistoryListItem->assembleMain(Object(ipl\Html\HtmlElement))
Icinga/icingaweb2#4 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(142): ipl\Web\Common\BaseListItem->createMain()
Icinga/icingaweb2#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(344): ipl\Web\Common\BaseListItem->assemble()
Icinga/icingaweb2#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
Icinga/icingaweb2#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
Icinga/icingaweb2#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
Icinga/icingaweb2#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
Icinga/icingaweb2#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
Icinga/icingaweb2#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
Icinga/icingaweb2#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
Icinga/icingaweb2#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
Icinga/icingaweb2#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
Icinga/icingaweb2#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
Icinga/icingaweb2#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\HtmlDocument->renderUnwrapped()
Icinga/icingaweb2#17 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
Icinga/icingaweb2#18 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): ipl\Web\Compat\ViewRenderer->render()
Icinga/icingaweb2#19 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
Icinga/icingaweb2#20 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(480): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
Icinga/icingaweb2#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
Icinga/icingaweb2#22 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
Icinga/icingaweb2#23 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
Icinga/icingaweb2#24 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
Icinga/icingaweb2#25 /usr/share/icingaweb2/public/index.php(4): require_once(String)
Icinga/icingaweb2#26 {main}
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.1
* Web browser used: Chrome  122.0.6261.112 
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`): PHP 7.2.24
* Server operating system and version: Rocky Linux release 8.9

**Comment by pbirokas** [comment]
We Are running a single Maria DB instance.

```
[root@icinga ~]# mysql --version
mysql  Ver 15.1 Distrib 10.3.39-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by lippserd** [comment]
> I could suggest to remove the invalid entries in `history`, but I think that is only a temporary solution and doesn't prevent new invalid entries.

Could be related to retention which leverages the missing constraints. @pbirokas Do you have retention enabled? Please share `config.yml#retention`. And how did you setup the database? Did you remove the [constraints](https://github.com/Icinga/icingadb/blob/main/schema/mysql/schema.sql#L1285)? Else, I have no explanation why they would be missing.

**Comment by pbirokas** [comment]
Here are the part from icingadb/config.yml
```
retention:
  history-days: 90
  sla-days: 90
  options:
    acknowledgement: 90
    comment: 90
    downtime: 90
    flapping: 90
    notification: 90
    state: 90
```

All icinga related DBs was setup with those lines:
```

CREATE DATABASE icingadb;
CREATE USER 'icingadb'@'localhost' IDENTIFIED BY '************';
GRANT ALL ON icingadb.* TO 'icingadb'@'localhost';

CREATE DATABASE icinga;
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga.* TO 'icinga'@'localhost' IDENTIFIED BY ''************';';

CREATE DATABASE icingaweb2;
CREATE USER 'icingaweb2'@'localhost' IDENTIFIED BY ''************';';
GRANT ALL ON icingaweb2.* TO 'icingaweb2'@'localhost';

CREATE DATABASE icinga_director CHARACTER SET 'utf8';
CREATE USER director@localhost IDENTIFIED BY ''************';';
GRANT ALL ON icinga_director.* TO director@localhost;

CREATE DATABASE vspheredb CHARACTER SET 'utf8mb4' COLLATE utf8mb4_bin;
CREATE USER vspheredb@localhost IDENTIFIED BY ''************';';
GRANT ALL ON vspheredb.* TO vspheredb@localhost;
```

**Comment by lippserd** [comment]
@pbirokas To be honest, I have no clue why the constraints wouldn't be there but you should clean the invalid rows and add the constraints.

**Comment by pbirokas** [comment]
@lippserd, since I am not expirienced in sql, can you provide me the queries do delete those entries and setup the constrains?

**Comment by lippserd** [comment]
Hi @pbirokas,

Please excuse the late reply. Please stop Icinga DB, execute the following statements in the Icinga DB database to delete incorrect/incomplete history data and make sure to add the constraints afterwards:

```sql
-- Delete notification events from the `history' table if its dependent row is missing in the `notification_history' table.
DELETE h FROM history h
LEFT JOIN notification_history sh ON sh.id = h.notification_history_id
WHERE h.event_type = "notification" AND sh.id IS NULL;

-- Delete rows from the `notification_history' table if its parent row is missing in the `history' table.
DELETE sh FROM notification_history sh
LEFT JOIN history h ON h.notification_history_id = sh.id
WHERE h.notification_history_id IS NULL;

-- Delete state events from the `history' table if its dependent row is missing in the `state_history' table.
DELETE h FROM history h
LEFT JOIN state_history sh ON sh.id = h.state_history_id
WHERE h.event_type = "state_change" AND sh.id IS NULL;

-- Delete rows from the `state_history' table if its parent row is missing in the `history' table.
DELETE sh FROM state_history sh
LEFT JOIN history h ON h.state_history_id = sh.id
WHERE h.state_history_id IS NULL;

-- Delete downtime events from the `history' table if its dependent row is missing in the `downtime_history' table.
DELETE h FROM history h
LEFT JOIN downtime_history sh ON sh.downtime_id = h.downtime_history_id
WHERE h.event_type IN ("downtime_start", "downtime_end") AND sh.downtime_id IS NULL;

-- Delete rows from the `downtime_history' table if its parent row is missing in the `history' table.
DELETE sh FROM downtime_history sh
LEFT JOIN history h ON h.downtime_history_id = sh.downtime_id
WHERE h.downtime_history_id IS NULL;

-- Delete comment events from the `history' table if its dependent row is missing in the `comment_history' table.
DELETE h FROM history h
LEFT JOIN comment_history sh ON sh.comment_id = h.comment_history_id
WHERE h.event_type IN ("comment_add", "comment_remove") AND sh.comment_id IS NULL;

-- Delete rows from the `comment_history' table if its parent row is missing in the `history' table.
DELETE sh FROM comment_history sh
LEFT JOIN history h ON h.comment_history_id = sh.comment_id
WHERE h.comment_history_id IS NULL;

-- Delete flapping events from the `history' table if its dependent row is missing in the `flapping_history' table.
DELETE h FROM history h
LEFT JOIN flapping_history sh ON sh.id = h.flapping_history_id
WHERE h.event_type IN ("flapping_start", "flapping_end") AND sh.id IS NULL;

-- Delete rows from the `flapping_history' table if its parent row is missing in the `history' table.
DELETE sh FROM flapping_history sh
LEFT JOIN history h ON h.flapping_history_id = sh.id
WHERE h.flapping_history_id IS NULL;

-- Delete acknowledgement events from the `history' table if its dependent row is missing in the `acknowledgement_history' table.
DELETE h FROM history h
LEFT JOIN acknowledgement_history sh ON sh.id = h.acknowledgement_history_id
WHERE h.event_type IN ("ack_set", "ack_clear") AND sh.id IS NULL;

-- Delete rows from the `acknowledgement_history' table if its parent row is missing in the `history' table.
DELETE sh FROM acknowledgement_history sh
LEFT JOIN history h ON h.acknowledgement_history_id = sh.id
WHERE h.acknowledgement_history_id IS NULL;
```

Best regards,
Eric

**Comment by julianbrost** [comment]
> Did you remove the [constraints](https://github.com/Icinga/icingadb/blob/main/schema/mysql/schema.sql?rgh-link-date=2024-03-14T13%3A00%3A38Z#L1285)? Else, I have no explanation why they would be missing.

I second that, these constraints were part of the `CREATE TABLE history` statement from v1.0.0 on: https://github.com/Icinga/icingadb/blob/v1.0.0/schema/mysql/schema.sql#L1253-L1287

So without any hint how they could have gone missing, there isn't much we can do here.
